#포트설정
server:
  port:  '8081'

#JSP설정
spring:  
  mvc:
    view:
      prefix:  /WEB-INF/views/
      suffix: .jsp

#SMTP설정
  mail:
    host:  smtp.gmail.com
    port:  '587'
    username: yunah1852@gmail.com
    password: iaha yxiy ikvy xcmg
    properties:  
      mail:
        debug:  'true'
        smtp:  
          connectiontimeout:  '5000'
          auth:  'false'
          starttls:
            enable:  'true'
            required:  'true'
      